In [1]:
import numpy as np

# Exercise 1

Write a function $\texttt{mydet(A)}$ that calculates the determinate of a given $n \times n$ matrix $A$ using Laplace Expansion. 

It should do the same as the $\texttt{numpy}$ function $\texttt{.det()}$:

In [2]:
A1 = np.array([[1,3,2,0],[1,1,2,3],[4,0,8,3],[2,5,4,5]])
A1, np.linalg.det(A1)

(array([[1, 3, 2, 0],
        [1, 1, 2, 3],
        [4, 0, 8, 3],
        [2, 5, 4, 5]]), 0.0)

In [3]:
A2 = np.array([[4,5,6,6],[7,7,9,-3],[8,4,0,-7],[-5,3,-6,-4]])
A2, np.linalg.det(A2)

(array([[ 4,  5,  6,  6],
        [ 7,  7,  9, -3],
        [ 8,  4,  0, -7],
        [-5,  3, -6, -4]]), -4485.0)

In [4]:
#this is how you define a function. 
#The body of the function is indented (like it is for for loops) - when the indentation end, the function ends.
def mydet(A):
    
    #define your function here. Declare a variable det whose value at the end should be the determinant 
    #of the given matrix A:
    
    return det

In [ ]:
#Test your function and compare with the numpy.linalg.det() function above:
mydet(A1), mydet(A2)

# Exercise 2

Write a function $\texttt{gauss(A,b)}$ that performs a Gaussian elimination on a $n \times m$ matrix $A$ and a $n \times 1$ vector $b$.

In [19]:
def gauss(A,b):
    
    #implement Gauss elimination and return the resulting matrix and vector:
    
    return A, b

In [20]:
#Test:
A = np.array([[1.,2.,3.],[-3.,4.,-5.],[5.,6.,7.]])
A

array([[ 1.,  2.,  3.],
       [-3.,  4., -5.],
       [ 5.,  6.,  7.]])

In [21]:
b = np.array([1.,2.,3.])
b

array([1., 2., 3.])

In [22]:
gauss(A,b)

(array([[ 5.        ,  6.        ,  7.        ],
        [ 0.        ,  7.6       , -0.8       ],
        [ 0.        ,  0.        ,  1.68421053]]), array([3. , 3.8, 0. ]))

# Exercise 3

Write a function $\texttt{im_base(A)}$ that returns the basis of the image of a function $f$ for which $A$ is the corresponding matrix. If you don't know how to do that by hand, ignore the exercise, or see the provided pdf.

In [23]:
def im_base(A):
    

In [25]:
A = np.array([[1.,2.,3.,4.],[2.,4.,7.,9.],[1.,2.,4.,5.]])
A

array([[1., 2., 3., 4.],
       [2., 4., 7., 9.],
       [1., 2., 4., 5.]])

In [26]:
im_base(A)

array([[1., 3.],
       [2., 7.],
       [1., 4.]])

# Exercise 4

Write a function rref(A) that returns the reduced row echelon form of a given matrix A.

In [13]:
#Test:
A = np.array([[1.,2.,3.,4.],[2.,4.,7.,9.],[1.,2.,4.,5.]])
A[1] = A[1]
A

array([[1., 2., 3., 4.],
       [2., 4., 7., 9.],
       [1., 2., 4., 5.]])

In [14]:
rref(A)

array([[1., 2., 0., 1.],
       [0., 0., 1., 1.],
       [0., 0., 0., 0.]])

# Exercise 5

Write a function ker_base(A) that returns the basis of the kernel of a function f for which A is the corresponding matrix. If you don't know how to find such a basis by hand, then ignore the exercise or see the provided pdf.

In [13]:
#Test:
A = np.array([[1.,2.,3.,4.],[2.,4.,7.,9.],[1.,2.,4.,5.]])
A

array([[1., 2., 3., 4.],
       [2., 4., 7., 9.],
       [1., 2., 4., 5.]])

In [14]:
ker_base(A)

array([[ 2.,  1.],
       [-1.,  0.],
       [ 0.,  1.],
       [ 0., -1.]])